theme: jekyll-theme-hacker
css: "style.css"
title: jonasbratland.com
logo: img/terminal_icon.png
sass:
  style: compressed  # Komprimerer den resulterende CSS-filen
  load_paths:
    - "."  # Dette legger til hovedmappen som et søkested for SCSS-filer
includes:
  - head
